### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ikamran64** [JeremyLinky/YouTube-VLN#6]
I am trying to pre-train the model but it is giving me the error. The error message indicates that there was an issue with decoding JSON data, most probably with the input string. I will share the error message below:

Loading model
Traceback (most recent call last):
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kamran-rehman/anaconda3/envs/lily/data/YouTube-VLN/pretrain.py", line 176, in <module>
    main()
  File "/home/kamran-rehman/anaconda3/envs/lily/data/YouTube-VLN/pretrain.py", line 54, in main
    config = BERT_CONFIG_FACTORY[args.model_name].from_json_file(args.config_file)
  File "/home/kamran-rehman/anaconda3/envs/lily/data/YouTube-VLN/vilbert/vilbert.py", line 182, in from_json_file
    params = json.load(fid)
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JeremyLinky** [comment]
It seems that this issue has been solved by #5. Glad to see that. :)
